[project]
name = "stack-settings"
version = "0.1.8"
description = "Pydantic global settings for the stack"
authors = [
    {name = "Admin", email= "admin@stack.local"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "pytz>=2025.1",
    "pydantic<3.0.0,>=2.0.0",
    "pydantic-settings<3.0.0,>=2.2.1"
]
