services:
  repository:
    build:
      context: pypiserver
    ports:
      - 8082:8082
    volumes:
      - repository-volume:/data/packages
    networks:
      - repository-network
    healthcheck:
      test: curl -s http://localhost:8082/ | grep -q "Welcome to pypiserver!" || exit 1
      interval: 60s
      retries: 20
      start_period: 5s
    develop:
      watch:
        - path: ./pypiserver/dist
          action: sync
          target: /data/packages
          ignore:
            - ./pypiserver/.gitkeep
            - ./pypiserver/.gitignore

volumes:
  repository-volume:

networks:
  repository-network: