services:
  repository:
    ports:
      - 8082:8082
    build:
      context: pypiserver
    volumes:
      - repository-volume:/data/packages
    networks:
      - repository-network
    healthcheck:
      test: curl -s http://localhost:8082/ | grep -q "Welcome to pypiserver!" || exit 1
      interval: 60s
      retries: 20
      start_period: 5s

volumes:
  repository-volume:

networks:
  repository-network: