"""sso

Revision ID: 05d63f4985d1
Revises: 60884f7304da
Create Date: 2025-03-02 23:10:46.850064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05d63f4985d1'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creation_time', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('sso_provider', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('sso_openid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sso_openid')
    op.drop_column('user', 'sso_provider')
    op.drop_column('user', 'creation_time')
    # ### end Alembic commands ###
