"""celery

Revision ID: 9dd23505d377
Revises: 05d63f4985d1
Create Date: 2025-09-24 11:49:47.935097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9dd23505d377'
down_revision = '05d63f4985d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    task_id_seq = Sequence('task_id_sequence')
    op.execute(CreateSequence(task_id_seq))
    op.create_table('celery_taskmeta',
        sa.Column(
            'id', sa.Integer(), task_id_seq,
            default=task_id_seq.next_value(),
            server_default=task_id_seq.next_value(), primary_key=True),
        sa.Column('task_id', sa.String(length=155), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.Column('traceback', sa.Text(), nullable=True),
        sa.Column('name', sa.String(length=155), nullable=True),
        sa.Column('args', sa.LargeBinary(), nullable=True),
        sa.Column('kwargs', sa.LargeBinary(), nullable=True),
        sa.Column('worker', sa.String(length=155), nullable=True),
        sa.Column('retries', sa.Integer(), nullable=True),
        sa.Column('queue', sa.String(length=155), nullable=True),
        sa.UniqueConstraint('task_id'),
    )
    taskset_id_seq = Sequence('taskset_id_sequence')
    op.execute(CreateSequence(taskset_id_seq))
    op.create_table('celery_tasksetmeta',
        sa.Column(
            'id', sa.Integer(), taskset_id_seq,
            default=taskset_id_seq.next_value(),
            server_default=taskset_id_seq.next_value(), primary_key=True),
        sa.Column('taskset_id', sa.String(length=155), nullable=True),
        sa.Column('result', sa.PickleType(), nullable=True),
        sa.Column('date_done', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('taskset_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_tasksetmeta')
    op.drop_table('celery_taskmeta')
    op.execute(DropSequence(Sequence('task_id_sequence')))
    op.execute(DropSequence(Sequence('taskset_id_sequence')))
    # ### end Alembic commands ###
