[project]
name = "stack-datamodel"
version = "0.1.4"
description = "SQLModel stack data model"
authors = [
    {name = "Admin", email= "admin@stack.local"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "sqlmodel<1.0.0,>=0.0.16",
    "email-validator<3.0.0,>=2.3.0"
]